name: Deploy to Cloud Functions without SA Key

on:
  push:
    branches:
      - main # トリガーにしたいブランチ名を指定

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud using Workload Identity Federation
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/873945717038/locations/global/workloadIdentityPools/ponzu-bot-pool/providers/github-provider
        service_account: ponzu-bot@penguin-garage.iam.gserviceaccount.com
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - run: |-
        python -m pip install poetry
      shell: bash
    - run: |-
          poetry export -f requirements.txt --without-hashes --output requirements.txt
      shell: bash
    - name: Deploy to Google Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: ponzu_bolt_app
        region: asia-northeast1
        runtime: python39 
        env_vars: SLACK_BOT_TOKEN=${{secrets.SLACK_BOT_TOKEN}},SLACK_APP_TOKEN=${{secrets.SLACK_APP_TOKEN}},OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}